spring:
  application:
    name: coffee-detect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coffeebean_detect
    username: root
    password: bape050622

  redis:
    host: localhost
    port: 6379
    database: 0

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  session:
    timeout: 86400 # 单位秒（=1天）
    store-type: redis

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.coffee: DEBUG