spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: springboot-init
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coffee_detect
    username: root
    password: bape050622
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
mybatis:
  mapper-locations: classpath:mapper/com/yupi/project/mapper/*.xml
  type-aliases-package: com.yupi.project.model.entity

logging:
  level:
    root: DEBUG
    org.springframework: TRACE
    org.hibernate: DEBUG
    com.zaxxer.hikari: DEBUG



